__prog__     = "steroids"
__pkg_name__ = "django-steroids"
__author__   = "Nestor Diaz"
__licence__  = "GNU General Public License v3 (GPLv3)"
__version__  = "0.1"
__desc__     = "A repository of Bootstrap CRUD templates for Django reusing features from django-crispy-forms, django-filters and django-tables2."
